version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: vulcan-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
  data-analysis:
    build:
      context: .
      dockerfile: Dockerfile.dataanalysis
    volumes:
      - ./data/goodreads.duckdb:/data/goodreads.duckdb:ro
      - ./runtime/plots:/app/runtime/plots
      - ./project_memory:/app/project_memory
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    working_dir: /app
    command: ["python", "src/agents/data_analysis_agent.py"]

volumes:
  redis-data:
    name: vulcan-redis-data 