version: '3.8'

services:
  dashboard:
    build: 
      context: .
      dockerfile: src/vulcan/frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./results:/app/results
      - ./config:/app/config
      - ./src:/app/src
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - PYTHONPATH=/app
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_SERVICE_URL=http://qdrant:6333

volumes:
  qdrant_data: 