# mkdocs.yml

site_name: AGENTIC - Autonomous Group Engineering for Next-generation Tabular Intelligence and Collaborative discovery
site_author: Nicolas Dehandschoewercker
site_description: >-
  An autonomous multi-agent system for strategic feature engineering 
  in recommender systems.

repo_url: https://github.com/nicolasfueceo/vulcan
repo_name: nicolasfueceo/vulcan
edit_uri: ""

copyright: Copyright &copy; 2025 Nicolas Dehandschoewercker

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - 'Home': 'index.md'
  - 'System Architecture': 'architecture.md'
  - 'Agent Manuals':
      - 'Discovery Team': 'agents/discovery_team.md'
      - 'Strategy Team': 'agents/strategy_team.md'
      - 'Downstream Agents': 'agents/downstream_agents.md'
  - 'Data Schema': 'data_schema.md'
  - 'Setup & Usage': 'setup.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
