[tool.ruff]
target-version = "py39"
line-length = 100
exclude = [".venv", "build", "dist"]

[tool.pyright]
typeCheckingMode = "basic"
pythonVersion = "3.9"

[tool.black]
target-version = ['py39']
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.coverage.run]
branch = true
omit = ["tests/*", "*/__init__.py"]
