api:
  cors_origins:
  - http://localhost:3000
  enabled: true
  host: localhost
  port: 8000
  reload: true
  websocket_enabled: true
configs_dir: config
data:
  test_db: data/test.db
  train_db: data/train.db
  validation_db: data/validation.db
debug_mode: false
evaluation:
  clustering_method: kmeans
  metrics:
  - silhouette_score
  - calinski_harabasz
  n_clusters_range:
  - 3
  - 5
  - 7
  - 10
  random_state: 42
  sample_size: 5000
experiment:
  experiment_name: null
  mlflow_enabled: false
  mlflow_tracking_uri: ./mlruns
  tags: []
  wandb_enabled: true
  wandb_entity: null
  wandb_project: vulcan-feature-engineering
llm:
  api_key_env: OPENAI_API_KEY
  max_retries: 3
  max_tokens: 2000
  model_name: gpt-4o-mini
  provider: openai
  rate_limit_delay: 0.5
  temperature: 0.7
logging:
  backup_count: 5
  file: vulcan.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10MB
  structured: true
mcts:
  agent_failure_strategy: skip_node
  exploration_factor: 1.414
  max_depth: 10
  max_iterations: 50
  reward_discount: 1.0
random_seed: 42
results_dir: results
states_dir: states
