# Default configuration parameters
# Empty for now

# Data paths
data:
  raw_dir: 'data/raw'
  interim_dir: 'data/interim'
  processed_dir: 'data/processed'

# Model parameters
models:
  emotion:
    model_type: 'transformer'
    embedding_dim: 768
    hidden_dim: 512
    num_labels: 6
  need:
    model_type: 'transformer'
    embedding_dim: 768
    hidden_dim: 512
    num_labels: 8
  recommendation:
    learning_rate: 0.001
    batch_size: 32
    epochs: 10

# Training parameters
training:
  learning_rate: 0.001
  batch_size: 32
  epochs: 10
  validation_split: 0.2

# Evaluation parameters
evaluation:
  metrics: ['accuracy', 'f1_score', 'precision', 'recall'] 