api:
  cors_origins:
  - http://localhost:3000
  enabled: true
  host: localhost
  port: 8000
  reload: true
  websocket_enabled: true
configs_dir: config
data:
  base_path: null
  inner_fold: 0
  outer_fold: 0
  sample_size: null
  test_db: data/test.db
  train_db: data/train.db
  validation_db: data/validation.db
debug_mode: false
evaluation:
  clustering_config:
    algorithm: kmeans
    cluster_range:
    - 2
    - 20
    dbscan_eps: 0.5
    dbscan_min_samples: 5
    metric: silhouette
    n_clusters: null
    optimize_n_clusters: true
  clustering_method: kmeans
  metrics:
  - silhouette_score
  - calinski_harabasz
  random_state: 42
  sample_size: 5000
  scoring_mode: cluster
experiment:
  description: null
  entity: null
  generation_size: 20
  max_features_in_set: 100
  max_generations: 10
  max_repair_attempts: 3
  min_features_in_set: 3
  mutation_rate: 0.3
  name: vulcan_experiment
  output_dir: experiments
  population_size: 50
  project_name: null
  random_seed: null
  save_artifacts: true
  tags: []
  tensorboard_enabled: false
  ucb_exploration_constant: 1.414
  wandb_enabled: false
llm:
  api_key_env: OPENAI_API_KEY
  max_retries: 3
  max_tokens: 2000
  model_name: gpt-4o-mini
  prompt_memory_max_features: null
  prompt_memory_type: full
  provider: openai
  rate_limit_delay: 0.5
  temperature: 0.7
logging:
  backup_count: 5
  file: vulcan.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  max_file_size: 10MB
  structured: true
random_seed: 42
results_dir: results
states_dir: states
