# VULCAN Default Configuration
# Versatile User-Learning Conversational Agent for Nudging

# Database Configuration
database:
  path: "data/goodreads.db"
  type: "sqlite"
  connection_timeout: 30
  max_retries: 3

# MCTS Configuration
mcts:
  max_iterations: 50
  exploration_constant: 1.414  # sqrt(2)
  max_depth: 10
  simulation_budget: 100
  parallel_workers: 4
  node_expansion_threshold: 5
  backup_strategy: "average"
  
# Parallel MCTS Configuration
parallel_mcts:
  enabled: true
  num_workers: 4
  batch_size: 10
  synchronization_interval: 5
  load_balancing: true

# Agent Configuration
agents:
  feature_agent:
    type: "llm"  # or "stub" for testing
    model: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 1000
    timeout: 30
    max_retries: 3
    
  reflection_agent:
    type: "llm"  # or "stub" for testing
    model: "gpt-3.5-turbo"
    temperature: 0.5
    max_tokens: 800
    timeout: 30
    max_retries: 3

# Feature Engineering Configuration
feature_engineering:
  max_features_per_iteration: 5
  feature_timeout: 60
  validation_enabled: true
  safety_checks: true
  allowed_imports:
    - "numpy"
    - "pandas"
    - "math"
    - "datetime"
    - "re"
  forbidden_operations:
    - "exec"
    - "eval"
    - "open"
    - "file"
    - "__import__"

# Evaluation Configuration
evaluation:
  metric: "silhouette_score"
  clustering_algorithm: "kmeans"
  n_clusters: 5
  test_size: 0.2
  cross_validation_folds: 3
  timeout: 120
  
# Cold Start Evaluation
cold_start:
  min_user_interactions: 5
  test_ratio: 0.2
  baseline_sample_size: 5000
  clustering_metric: "silhouette_score"

# Reflection Configuration
reflection:
  enabled: true
  frequency: 5  # Every 5 iterations
  memory_size: 100
  insight_threshold: 0.1
  reflection_types:
    - "feature_proposal"
    - "evaluation_result"
    - "strategy_adjustment"

# State Management
state:
  save_frequency: 10  # Save every 10 iterations
  max_history_size: 1000
  checkpoint_enabled: true
  checkpoint_directory: "checkpoints"
  session_timeout: 3600  # 1 hour

# Sandbox Configuration
sandbox:
  enabled: true
  timeout: 30
  memory_limit: "512MB"
  cpu_limit: 1.0
  temp_directory: "/tmp/vulcan_sandbox"
  cleanup_on_exit: true

# Visualization Configuration
visualization:
  enabled: true
  update_interval: 5
  max_history: 100
  dashboard_port: 8050
  save_plots: true
  plot_directory: "plots"

# Monitoring Configuration
monitoring:
  enabled: true
  log_level: "INFO"
  buffer_size: 100
  metrics_collection: true
  performance_tracking: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "vulcan.log"
  max_file_size: "10MB"
  backup_count: 5

# LLM Configuration (if using external LLM services)
llm:
  provider: "openai"  # or "anthropic", "local"
  api_key_env: "OPENAI_API_KEY"
  base_url: null
  organization: null
  rate_limit: 60  # requests per minute
  retry_delay: 1.0

# Performance Configuration
performance:
  max_memory_usage: "2GB"
  gc_frequency: 100  # iterations
  profiling_enabled: false
  optimization_level: 1

# Security Configuration
security:
  code_validation: true
  input_sanitization: true
  output_filtering: true
  allowed_file_extensions: [".py", ".txt", ".json", ".yaml"]
  max_file_size: "1MB"

# Experimental Features
experimental:
  adaptive_exploration: false
  dynamic_feature_weighting: false
  multi_objective_optimization: false
  transfer_learning: false 