mcts:
  max_iterations: 50
  exploration_factor: 1.414
  reward_discount: 1.0
  max_depth: 10
  agent_failure_strategy: skip_node
llm:
  provider: openai
  model_name: gpt-4o-mini
  temperature: 0.7
  max_tokens: 2000
  max_retries: 3
  rate_limit_delay: 0.5
  api_key_env: OPENAI_API_KEY
  prompt_memory_type: full
  prompt_memory_max_features: null
evaluation:
  sample_size: 5000
  random_state: 42
  metrics:
  - silhouette_score
  - calinski_harabasz
  clustering_method: kmeans
  clustering_config:
    n_clusters: null
    cluster_range:
    - 2
    - 20
    metric: silhouette
    optimize_n_clusters: true
    algorithm: kmeans
    dbscan_eps: 0.5
    dbscan_min_samples: 5
  scoring_mode: cluster
api:
  enabled: true
  host: localhost
  port: 8000
  reload: true
  cors_origins:
  - http://localhost:3000
  websocket_enabled: true
experiment:
  name: vulcan_experiment
  description: null
  output_dir: experiments
  tags: []
  wandb_enabled: false
  project_name: null
  entity: null
  tensorboard_enabled: false
  max_features_in_set: 100
  min_features_in_set: 3
  max_generations: 10
  random_seed: null
  save_artifacts: true
data:
  train_db: data/train.db
  test_db: data/test.db
  validation_db: data/validation.db
  base_path: null
  outer_fold: 1
  inner_fold: 1
  sample_size: null
logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: vulcan.log
  max_file_size: 10MB
  backup_count: 5
  structured: true
results_dir: results
states_dir: states
configs_dir: config
random_seed: 42
debug_mode: false 