# VULCAN Configuration File
# Autonomous Feature Engineering for Recommender Systems

# MCTS Algorithm Configuration
mcts:
  max_iterations: 50
  exploration_factor: 1.414
  reward_discount: 1.0
  max_depth: 10
  agent_failure_strategy: "skip_node"

# LLM Configuration
llm:
  provider: "openai"
  model_name: "gpt-4o"
  temperature: 0.7
  max_tokens: 8000  # Higher limit for more detailed responses
  max_retries: 3
  rate_limit_delay: 0.5
  api_key_env: "OPENAI_API_KEY"

# Feature Evaluation Configuration
evaluation:
  sample_size: 5000
  random_state: 42
  metrics:
    - "silhouette_score"
    - "calinski_harabasz"
  clustering_method: "kmeans"
  clustering_config:
    n_clusters: null  # Will be optimized
    cluster_range: [2, 20]
    metric: "silhouette"
    optimize_n_clusters: true

# API Server Configuration
api:
  enabled: true
  host: "localhost"
  port: 8000
  reload: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
  websocket_enabled: true

# Experiment Tracking Configuration
experiment:
  max_features: 100
  min_features: 3
  feature_selection_size: 20
  save_results: true
  results_dir: "results"
  log_level: "INFO"
  experiment_name: "vulcan_experiment"

# Data Configuration
data:
  train_db: "data/train.db"
  test_db: "data/test.db"
  validation_db: "data/validation.db"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "vulcan.log"
  max_file_size: "10MB"
  backup_count: 5
  structured: true

# Directory Configuration
results_dir: "results"
states_dir: "states"
configs_dir: "config"

# System Configuration
random_seed: 42
debug_mode: false 